# Use postgres/example user/password credentials
version: '3.1'

services:

  # postgres:
  #   image: postgres
  #   environment:
  #     POSTGRES_PASSWORD: ppooii12
  #     POSTGRES_DB: 'basic-auth'
  #   ports:
  #     - 5066:5432
  #   volumes:
  #     - './db:/var/lib/postgres'

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
  #     PGADMIN_DEFAULT_PASSWORD: ppooii12
  #   ports:
  #     - 5050:80
  #   depends_on:
  #     - postgres

  redis:
    image: redis
    command: redis-server
    hostname: redis
    ports:
      - 6379:6379

  redis-commander:
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "5051:8081"
    depends_on:
      - redis

  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail
    domainname: example.com
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ENABLE_SASLAUTHD=0
      - ONE_DIR=1
      - DMS_DEBUG=0
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
